project:
  type: website
  output-dir: _site

website:
  title: "Yanyu Li"
  description: "Speech perception | Prosody | Experimental methods"
  navbar:
    left:
      - text: "Welcome"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: cv.qmd
  page-footer:
    left: "Copyright 2026, Yanyu Li"
    right:
      - text: "GitHub"
        href: "https://github.com/yanyuulii"
      - text: "Google Scholar"
        href: "https://scholar.google.com/citations?user=gXpRx9UAAAAJ&hl=en"

format:
  html:
    smooth-scroll: true
    respect-user-color-scheme: true
    include-after-body: assets/theme-toggle-fix.js
    theme: 
      light: Flatly
      dark:  Darkly
    toc: false
